// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rep-report/Email.tsx": () => import("../components/mockups/rep-report/Email.tsx"),
  "./components/mockups/rep-report/Portal.tsx": () => import("../components/mockups/rep-report/Portal.tsx")
};
