import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Sparkles,
  Copy,
  Check,
  RefreshCw,
  ChevronDown,
  ChevronUp,
  Database,
  Loader2,
  AlertCircle,
  Wand2,
  ThumbsUp,
  ThumbsDown,
  PenLine,
  MessageSquare,
} from "lucide-react";
import { cn } from "@/lib/utils";

interface DraftEmailModalProps {
  open: boolean;
  onClose: () => void;
  accountId?: string | null;
  contactId?: string | null;
  threadId?: string | null;
  targetMessageId?: string | null;
  defaultPlayType?: string;
  companyName?: string;
  contactName?: string;
}

interface DataAnchor {
  type: string;
  label: string;
  value: string;
}

interface DraftResponse {
  draft: string;
  playLabel: string;
  playType: string;
  dataAnchors: DataAnchor[];
  voiceProfileAvailable: boolean;
  voiceProfileSampleCount: number;
}

interface PlayType {
  value: string;
  label: string;
  intent: string;
}

export function DraftEmailModal({
  open,
  onClose,
  accountId,
  contactId,
  threadId,
  targetMessageId,
  defaultPlayType = "general",
  companyName,
  contactName,
}: DraftEmailModalProps) {
  const isThreadReply = !!threadId;
  // For thread replies, default to "thread_reply" unless the caller passed a
  // more specific play type (e.g. the Smarter Conversations suggestion card
  // sends "quote_request_reply" so the draft is biased toward a rate response).
  const initialPlayType = isThreadReply
    ? (defaultPlayType && defaultPlayType !== "general" ? defaultPlayType : "thread_reply")
    : defaultPlayType;
  const [playType, setPlayType] = useState(initialPlayType);
  const [draft, setDraft] = useState("");
  const [draftResponse, setDraftResponse] = useState<DraftResponse | null>(null);
  const [copied, setCopied] = useState(false);
  const [showAnchors, setShowAnchors] = useState(false);
  const [additionalContext, setAdditionalContext] = useState("");
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [feedbackRating, setFeedbackRating] = useState<"good" | "bad" | "needs_work" | null>(null);
  const [feedbackNotes, setFeedbackNotes] = useState("");
  const [feedbackSubmitted, setFeedbackSubmitted] = useState(false);
  const [showFeedbackNotes, setShowFeedbackNotes] = useState(false);
  const { toast } = useToast();

  const { data: playTypes = [] } = useQuery<PlayType[]>({
    queryKey: ["/api/email-drafts/play-types"],
    enabled: !isThreadReply,
  });

  const generateMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", "/api/email-drafts/generate", {
        accountId: accountId || undefined,
        contactId: contactId || undefined,
        playType,
        threadId: threadId || undefined,
        targetMessageId: targetMessageId || undefined,
        additionalContext: additionalContext || undefined,
      });
      return res.json() as Promise<DraftResponse>;
    },
    onSuccess: (data) => {
      setDraft(data.draft);
      setDraftResponse(data);
    },
    onError: () => {
      toast({ title: "Failed to generate draft", variant: "destructive" });
    },
  });

  const feedbackMutation = useMutation({
    mutationFn: async (params: { rating: "good" | "bad" | "needs_work"; notes?: string }) => {
      const res = await apiRequest("POST", "/api/email-drafts/feedback", {
        rating: params.rating,
        notes: params.notes || undefined,
        draftText: draftResponse?.draft || "",
        editedText: draft !== draftResponse?.draft ? draft : undefined,
        playType: draftResponse?.playType || playType,
        playLabel: draftResponse?.playLabel,
        threadId: threadId || undefined,
        accountId: accountId || undefined,
        contactId: contactId || undefined,
        contactName: contactName || undefined,
        voiceProfileUsed: draftResponse?.voiceProfileAvailable ?? false,
      });
      return res.json();
    },
    onSuccess: () => {
      setFeedbackSubmitted(true);
      toast({ title: "Feedback saved", description: "Your feedback will improve future drafts." });
    },
    onError: () => {
      toast({ title: "Failed to save feedback", variant: "destructive" });
    },
  });

  function handleFeedback(rating: "good" | "bad" | "needs_work") {
    setFeedbackRating(rating);
    if (rating === "good") {
      setShowFeedbackNotes(false);
      feedbackMutation.mutate({ rating, notes: feedbackNotes || undefined });
    } else {
      setShowFeedbackNotes(true);
    }
  }

  function handleSubmitFeedbackWithNotes() {
    if (!feedbackRating) return;
    feedbackMutation.mutate({ rating: feedbackRating, notes: feedbackNotes || undefined });
  }

  if (open && isThreadReply && !autoGenerated && !draftResponse && !generateMutation.isPending) {
    setAutoGenerated(true);
    setTimeout(() => generateMutation.mutate(), 0);
  }

  function handleGenerate() {
    generateMutation.mutate();
  }

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(draft);
      setCopied(true);
      toast({ title: "Draft copied to clipboard" });
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast({ title: "Unable to copy — please select and copy manually", variant: "destructive" });
    }
  }

  function handleRegenerate() {
    setFeedbackRating(null);
    setFeedbackNotes("");
    setFeedbackSubmitted(false);
    setShowFeedbackNotes(false);
    generateMutation.mutate();
  }

  function handleClose() {
    setDraft("");
    setDraftResponse(null);
    setCopied(false);
    setShowAnchors(false);
    setAdditionalContext("");
    setAutoGenerated(false);
    setFeedbackRating(null);
    setFeedbackNotes("");
    setFeedbackSubmitted(false);
    setShowFeedbackNotes(false);
    onClose();
  }

  const isLoading = generateMutation.isPending;

  return (
    <Dialog open={open} onOpenChange={(v) => { if (!v) handleClose(); }}>
      <DialogContent className="sm:max-w-lg" data-testid="draft-email-modal">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-amber-400" />
            {isThreadReply ? "Draft Reply" : "Draft Email"}
            {companyName && (
              <span className="text-sm font-normal text-muted-foreground">
                — {companyName}
              </span>
            )}
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          {!isThreadReply && (
            <div className="flex items-center gap-3">
              <div className="flex-1">
                <label className="text-xs font-medium text-muted-foreground mb-1 block">Play</label>
                <Select value={playType} onValueChange={setPlayType}>
                  <SelectTrigger className="h-8 text-xs" data-testid="select-play-type">
                    <SelectValue placeholder="Select play type" />
                  </SelectTrigger>
                  <SelectContent>
                    {playTypes.map((pt) => (
                      <SelectItem key={pt.value} value={pt.value} className="text-xs">
                        {pt.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              {contactName && (
                <div className="text-xs text-muted-foreground pt-4">
                  To: <span className="font-medium text-foreground">{contactName}</span>
                </div>
              )}
            </div>
          )}

          {!isThreadReply && (
            <div>
              <label className="text-xs font-medium text-muted-foreground mb-1 block">
                Additional context (optional)
              </label>
              <Textarea
                value={additionalContext}
                onChange={(e) => setAdditionalContext(e.target.value)}
                placeholder="e.g., They mentioned rate concerns last call..."
                className="h-16 text-xs resize-none"
                data-testid="input-additional-context"
              />
            </div>
          )}

          {!draftResponse && !isLoading && !isThreadReply && (
            <Button
              onClick={handleGenerate}
              className="w-full gap-2"
              data-testid="button-generate-draft"
            >
              <Wand2 className="w-4 h-4" />
              Generate Draft
            </Button>
          )}

          {isLoading && (
            <div className="flex items-center justify-center py-8 gap-2 text-muted-foreground" data-testid="draft-loading">
              <Loader2 className="w-5 h-5 animate-spin" />
              <span className="text-sm">Generating personalized draft...</span>
            </div>
          )}

          {draftResponse && !isLoading && (
            <>
              <div className="flex items-center gap-2 flex-wrap">
                <Badge variant="outline" className="text-xs gap-1" data-testid="badge-play-label">
                  <Sparkles className="w-3 h-3" />
                  {draftResponse.playLabel}
                </Badge>
                {draftResponse.voiceProfileAvailable ? (
                  <Badge variant="secondary" className="text-xs" data-testid="badge-voice-profile">
                    Voice matched ({draftResponse.voiceProfileSampleCount} emails)
                  </Badge>
                ) : (
                  <Badge variant="outline" className="text-xs text-amber-600 border-amber-300" data-testid="badge-no-voice">
                    <AlertCircle className="w-3 h-3 mr-1" />
                    No voice profile — generic tone
                  </Badge>
                )}
              </div>

              <div>
                <label className="text-xs font-medium text-muted-foreground mb-1 block">
                  Email Draft
                </label>
                <Textarea
                  value={draft}
                  onChange={(e) => setDraft(e.target.value)}
                  className="min-h-[120px] text-sm"
                  data-testid="textarea-draft"
                />
              </div>

              {draftResponse.dataAnchors.length > 0 && (
                <div>
                  <button
                    onClick={() => setShowAnchors(!showAnchors)}
                    className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors"
                    data-testid="button-toggle-anchors"
                  >
                    <Database className="w-3 h-3" />
                    Data Anchors ({draftResponse.dataAnchors.length})
                    {showAnchors ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
                  </button>
                  {showAnchors && (
                    <div className="mt-2 p-3 rounded-lg bg-muted/50 border space-y-1.5" data-testid="data-anchors-section">
                      {draftResponse.dataAnchors.map((anchor, i) => (
                        <div key={i} className="flex items-start gap-2 text-xs" data-testid={`data-anchor-${anchor.type}`}>
                          <span className="font-medium text-muted-foreground min-w-[100px] shrink-0">
                            {anchor.label}:
                          </span>
                          <span className="text-foreground">{anchor.value}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}

              <div className="border-t pt-3" data-testid="feedback-section">
                {feedbackSubmitted ? (
                  <div className="flex items-center gap-2 text-xs text-emerald-600 dark:text-emerald-400" data-testid="feedback-submitted">
                    <Check className="w-4 h-4" />
                    <span className="font-medium">Feedback saved — this will shape future drafts</span>
                  </div>
                ) : (
                  <div className="space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-medium text-muted-foreground">Rate this draft</span>
                      <div className="flex items-center gap-1">
                        <Button
                          size="sm"
                          variant="ghost"
                          className={cn(
                            "h-7 px-2 gap-1 text-xs",
                            feedbackRating === "good" && "bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300"
                          )}
                          onClick={() => handleFeedback("good")}
                          disabled={feedbackMutation.isPending}
                          data-testid="button-feedback-good"
                        >
                          <ThumbsUp className="w-3.5 h-3.5" />
                          Good
                        </Button>
                        <Button
                          size="sm"
                          variant="ghost"
                          className={cn(
                            "h-7 px-2 gap-1 text-xs",
                            feedbackRating === "needs_work" && "bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300"
                          )}
                          onClick={() => handleFeedback("needs_work")}
                          disabled={feedbackMutation.isPending}
                          data-testid="button-feedback-needs-work"
                        >
                          <PenLine className="w-3.5 h-3.5" />
                          Needs Work
                        </Button>
                        <Button
                          size="sm"
                          variant="ghost"
                          className={cn(
                            "h-7 px-2 gap-1 text-xs",
                            feedbackRating === "bad" && "bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-300"
                          )}
                          onClick={() => handleFeedback("bad")}
                          disabled={feedbackMutation.isPending}
                          data-testid="button-feedback-bad"
                        >
                          <ThumbsDown className="w-3.5 h-3.5" />
                          Off
                        </Button>
                      </div>
                    </div>

                    {showFeedbackNotes && (
                      <div className="space-y-2">
                        <Textarea
                          value={feedbackNotes}
                          onChange={(e) => setFeedbackNotes(e.target.value)}
                          placeholder={
                            feedbackRating === "bad"
                              ? "What was wrong? (e.g., too formal, wrong tone, irrelevant info...)"
                              : "What should change? (e.g., shorter, more direct, reference the rate...)"
                          }
                          className="h-16 text-xs resize-none"
                          data-testid="input-feedback-notes"
                        />
                        <div className="flex justify-end">
                          <Button
                            size="sm"
                            className="h-7 text-xs gap-1"
                            onClick={handleSubmitFeedbackWithNotes}
                            disabled={feedbackMutation.isPending}
                            data-testid="button-submit-feedback"
                          >
                            {feedbackMutation.isPending ? (
                              <Loader2 className="w-3 h-3 animate-spin" />
                            ) : (
                              <MessageSquare className="w-3 h-3" />
                            )}
                            Submit Feedback
                          </Button>
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            </>
          )}
        </div>

        {draftResponse && !isLoading && (
          <DialogFooter className="flex-col gap-3 sm:flex-col">
            {isThreadReply && (
              <div className="w-full">
                <label className="text-xs font-medium text-muted-foreground mb-1 block">
                  Direction for regeneration (optional)
                </label>
                <Textarea
                  value={additionalContext}
                  onChange={(e) => setAdditionalContext(e.target.value)}
                  placeholder="e.g., Be firmer on rate, mention our on-time performance..."
                  className="h-14 text-xs resize-none"
                  data-testid="input-thread-direction"
                />
              </div>
            )}
            <div className="flex items-center gap-2 w-full justify-end">
            <Button
              variant="outline"
              size="sm"
              onClick={handleRegenerate}
              className="gap-1"
              data-testid="button-regenerate-draft"
            >
              <RefreshCw className="w-3 h-3" />
              Regenerate
            </Button>
            <Button
              size="sm"
              onClick={handleCopy}
              className="gap-1"
              data-testid="button-copy-draft"
            >
              {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
              {copied ? "Copied!" : "Copy to Clipboard"}
            </Button>
            </div>
          </DialogFooter>
        )}
      </DialogContent>
    </Dialog>
  );
}
